Extract jvm version from openjdk vulnerabilities group
adoptium/temurin-vdr-generator pull request #3
Opened 2024-04-23 17:29 UTC by Scanteianu

2024-04-24 08:13 UTC, karianna requested changes

2024-04-24 08:13 UTC, karianna commented on cvereporter/fetch_vulnerabilities.py
> +        # print(r)
Remove commented out code?

2024-04-24 08:13 UTC, karianna commented on cvereporter/fetch_vulnerabilities.py
> +            if "CVE ID" in header.text:
extract to its own function?

2024-04-24 08:13 UTC, karianna commented on cvereporter/fetch_vulnerabilities.py
> +            for version in extracted_affected:
Would be good to have a comment showing some sample data.

2024-04-24 08:13 UTC, karianna commented on cvereporter/nist_enhance.py
> +        # for now - we use ojvg's version extraction
Maybe expand on what ojvg is

2024-04-24 08:13 UTC, karianna commented on tests/test_pipeline.py
> +# to run just one test: python3 -m pytest -v -k test_fetch -s (in this case, runs "test_fetch")
```suggestion
# To run a single test: python3 -m pytest -v -k test_fetch -s (in this case, runs "test_fetch")
```

2024-04-24 12:36 UTC, Scanteianu commented
thanks @karianna for the review, i think i addressed everything

2024-04-25 09:34 UTC, karianna approved these changes

2024-04-25 16:24 UTC, smlambert approved these changes

2024-04-25 16:25 UTC, merged